### ISSUE TITLE
JSON Keys Parser

### ISSUE THREAD

**Issue by Skillz4Killz** [jamiebuilds/json-parser-in-typescript-very-bad-idea-please-dont-use#3]
Could you theoretically use this json files keys? What I was hoping was if it was possible to process an entire folder of json files to get the keys for i18next strings. Then you could simply have a type made for every single translation key. Auto-completion would be amazing at that point. You would be instantly able to tell when a string is missing hasnt been translated. You would never make a mistake with a typo of pressing the wrong key. 

That would make this from a very bad idea to the best idea of the century!

**Comment by jamiebuilds** [comment]
I believe in you

**Comment by olee** [comment]
Though at that point I think a tool to generate type information files from the translations would be way more efficient and not cripple the TS type checker xD
